### ISSUE TITLE
Cannot GET 

### ISSUE THREAD

**Issue by KimBerry** [wri/gfw-fires-app#28]
After following the quick start instructions I copied the Local url into my browser. The localhost:3000 simply displayed 'Cannot GET'. 

The Quickstart generated the following;

kberrys-MacBook-Pro:git kberry$ git clone https://github.com/wri/gfw-fires-app.git
Cloning into 'gfw-fires-app'...
remote: Counting objects: 20027, done.
remote: Compressing objects: 100% (184/184), done.
remote: Total 20027 (delta 121), reused 0 (delta 0), pack-reused 19842
Receiving objects: 100% (20027/20027), 28.25 MiB | 6.31 MiB/s, done.
Resolving deltas: 100% (14145/14145), done.

Then;
 Local: http://localhost:3000
 External: http://10.0.3.214:3000

**Comment by SwampGuzzler** [comment]
@KimBerry We have two issues here. First things first: although the server is pointing to port 3000, we actually need to paste our /pageLocation into the url. So, for the home page: http://localhost:3000/home or the map page: http://localhost:3000/map, etc.

The other issue is that you will need to run an 'npm install' to read the package.json and install all of the required node dependencies this project runs on. I couldn't tell from your screenshot if you had run an 'npm install' after you cloned the repo.

**Comment by KimBerry** [comment]
I did run 'npm install' and it generated;

[fsevents] Success: "/Users/kberry/git/gfw-fires-app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> gifsicle@3.0.4 postinstall /Users/kberry/git/gfw-fires-app/node_modules/gifsicle
> node lib/install.js
  ✔ gifsicle pre-build test passed successfully
> jpegtran-bin@3.2.0 postinstall /Users/kberry/git/gfw-fires-app/node_modules/jpegtran-bin
> node lib/install.js
  ✔ jpegtran pre-build test passed successfully
> optipng-bin@3.1.2 postinstall /Users/kberry/git/gfw-fires-app/node_modules/optipng-bin
> node lib/install.js
  ✔ optipng pre-build test passed successfully
> flow-bin@0.24.2 postinstall /Users/kberry/git/gfw-fires-app/node_modules/flow-bin
> node lib/install.js
  ✔ flow binary test passed successfully
> gfw-fires-app@3.2.79 install /Users/kberry/git/gfw-fires-app
> bower install
.....

**Comment by SwampGuzzler** [comment]
You will also have to run 'npm start', which compiles the code and starts up the local server (which points to Port 3000 be default).

**Comment by KimBerry** [comment]
I did run 'npm start' again and it seems to work. Thank you! After following the link above it directs me to the website.
