### ISSUE TITLE
Trying to connect different google earth engine map to GFW fire app

### ISSUE THREAD

**Issue by bfhouse** [wri/gfw-fires-app#33]
Hello,
I am have a project I am working on where I am trying to use your GFW Fires App to display a different google earth engine map but I could not find the spot where you have the map's url. What do I need to do to change the app so that it points to my GEE page? 
Thanks,

**Comment by SwampGuzzler** [comment]
If I understand you correctly, and you would like the entire GFW Fires application but not the map page (and to have fires/map point to your Google Earth Engine page), you need to change the contents of map.jade, which builds into map.html and takes control of fires/map.

To do this, you need to remove everything in map.jade and have that link to your page.

Bear in mind, this would render everything in map/js, map/css, map/html, and map/php unnecessary. 

If you want to embed your Google Earth Engine map into the page, that transition will not be seamless and would require a lot of re-writing.

**Comment by SwampGuzzler** [comment]
@bfhouse If you have no more questions right now, I'm going to ahead and close this from inactivity.

**Comment by bfhouse** [comment]
Sounds good. Turns out we realized your fires app(which is the app we were
wanting to use) is based on Arc rather than Google earth engine. I might
make the suggestion that you document that somewhere in the github repo.
Thanks,
Bfhouse
